apiVersion: apps/v1
kind: Deployment  
metadata:
  name: case-study-deployment
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 3 
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask 
        image: kennethcruz/kencruzcapstone:latest
        ports:
        - containerPort: 8070
---
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
 # service maps the pods into one IP address
apiVersion: v1
kind: Service
metadata:
  name: case-study-service 
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
      nodePort: 30004