apiVersion: apps/v1
kind: Deployment  
metadata:
  name: case-study
spec:
  selector:
    matchLabels:
      app: capstone-project-ken-cruz-deployment
  replicas: 3 
  template:
    metadata:
      labels:
        app:
    spec:
      containers:
      - name: capstone-project-container 
        image: kenneth-cruz/app-sba-kubernetes-cluster:1.0
        ports:
        - containerPort: 8090 
---
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
 # service maps the pods into one IP address
apiVersion: v1
kind: Service
metadata:
  name: capstone-project-ken-cruz-service 
spec:
  type: NodePort
  selector:
    app: case-study
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30008